version: '3.8'
services:
    scaffold-build:
        extends:
            file: docker-compose-common.yml
            service: scaffold-build

    frontend-build:
        extends:
            file: docker-compose-common.yml
            service: frontend-build

    scaffold-deploy:
        build:
            context: .
            dockerfile: Dockerfile.Node
        command: yarn deploy --network optimismSepolia
        volumes:
            - ./smartcontracts:/workspace
        env_file:
            - .env
        depends_on:
            scaffold-build:
                condition: service_completed_successfully

    frontend-deploy:
        build:
            context: .
            dockerfile: Dockerfile.Node
        command: sh -c "yarn build && yarn start"
        volumes:
            - ./frontend:/workspace
        env_file:
            - .env
        depends_on:
            scaffold-deploy:
                condition: service_completed_successfully
        ports:
            - '3333:3333'

    offchain-deploy:
        build:
            context: .
            dockerfile: Dockerfile.Python
        command: python3 main.py
        volumes:
            - ./offchain:/workspace
            - ./smartcontracts/packages/hardhat/deployments:/deployments
        env_file:
            - .env
        depends_on:
            scaffold-deploy:
                condition: service_completed_successfully
