name: Docker Compose Test Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Test containers
              run: docker compose -f "docker-compose-test.yml" up --build

            - name: Get test results
              run: |
                  container_id=$(docker ps -aqf "name=scaffold-test")
                  if [ -z "$container_id" ]; then
                      echo "::error::Failed to get the scaffold-test container ID"
                  else
                      exit_code=$(docker inspect -f '{{.State.ExitCode}}' $container_id)
                      echo "Test container exit code: $exit_code"
                      if [ "$exit_code" != "0" ]; then
                      echo "::error::Tests failed"
                      exit 1
                  fi

            - name: Get scaffold-test logs
              run: docker compose -f "docker-compose-test.yml" logs scaffold-test &> ./scaffold-test.log

            - name: Archive scaffold-test logs
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: docker-logs
                  path: .*.log

            - name: Cleanup
              run: docker compose -f "docker-compose-test.yml" down
